/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

export const  CarBody = forwardRef(({ args = [1.7, 1, 4], mass = 1000, ...props }, ref) =>{

  useEffect(()=>{
    console.log('ref', ref)
  },[])
  const { nodes, materials } = useGLTF('/models/carOne.glb');
  // const { nodes, materials } = useGLTF('/Beetle.glb')
  const [, api] = useBox(() => ({ mass, args, allowSleep: false, onCollide: (e) => console.log('bonk', e.body.userData), ...props }), ref)


  return (
    <mesh ref={ref} api={api}>
    <group {...props} dispose={null} position={[0, 5, 0]}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Paint} />
      <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials.Tyre} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials.Window} />
      <mesh geometry={nodes.Cube_5.geometry} material={materials.Chrome} />
      <group position={[1.18, 0.03, 2.37]} rotation={[Math.PI / 2, 0, 0]} scale={[0.28, 0.23, 0.28]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.Paint} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials.Window} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials.Breaklight} />
      </group>
      <group position={[1.71, 0.55, 0.77]} rotation={[0, 0.2, 0]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Paint} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Window} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Chrome} position={[0, 0.02, -2.33]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Chrome} position={[0.96, 0.61, -2.34]} scale={[0.07, 0.19, 0.13]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Paint} position={[-0.7, 0.82, -2.54]} scale={[0.71, 0.05, 0.18]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Chrome} position={[-1.16, -0.59, -2.34]} rotation={[Math.PI / 2, 0, 0]} scale={[0.12, 0.22, 0.12]} />
      <group position={[1.64, -0.45, 1.59]} rotation={[0, 0, -Math.PI / 2]} scale={[0.47, 0.15, 0.47]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Tyre} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Chrome} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Chrome} position={[0.6, -0.45, -2.43]} scale={[0.05, 0.13, 0.13]} />
    </group>
    </mesh>
  )
})

useGLTF.preload('/models/carOne.glb')
