/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { forwardRef, useRef } from "react";
import { useCylinder } from "@react-three/cannon";


export const Wheel = forwardRef(({ radius = 10, leftSide, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/models/wheel2.glb')

  useCylinder(
    () => ({
      mass: 1,
      type: "Kinematic",
      material: "wheel",
      collisionFilterGroup: 0,
      args: [radius, radius, 0.5, 16],
      ...props,
    }),
    ref
  );
  return (
    <mesh ref={ref}>
    <group {...props} dispose={null}>
      <group rotation={[0, 0, ((leftSide ? 1 : -1) * Math.PI) / 2]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.Tyre} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Chrome} />
      </group>
    </group>
    </mesh>
  )
});

useGLTF.preload('/models/wheel2.glb')
