import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Image from "next/image";
import { Suspense } from "react";
import Scene from "../components/Scene";
import SceneTwo from "../components/SceneTwo";
import SelfDriveScene from "../components/SelfDriveScene";
import styles from "../styles/Home.module.css";
import { Debug, Physics, useCylinder, usePlane } from '@react-three/cannon'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: "100vw", height: "100vh" }} className={styles.main}>
        <Canvas>
          <Suspense fallback={null}>
            {/* <SceneTwo /> */}
            {/* <Scene /> */}
            <Physics
              broadphase="SAP"
              contactEquationRelaxation={4}
              friction={1e-3}
              allowSleep
            >
              <Debug />
              <SelfDriveScene />
            </Physics>
          </Suspense>
        </Canvas>
      </main>
    </div>
  );
}
